#Server and Logging errors
server.port = 8090
spring.application.name=Cvtheque
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=ERROR
spring.jackson.serialization.fail-on-empty-beans=false

#Storage Service
spring.servlet.multipart.max-file-size=50000KB
spring.servlet.multipart.max-request-size=50000KB

#https://code.danielfrak.com/spring-boot-best-practice-disable-osiv-to-start-receiving-lazyinitializationexception-warnings-again/
#spring.jpa.open-in-view=false

#Tuning Hikari Configuration Parameters
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000

###Database : POSTGRESQL
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

###Database : datasource Locale
#spring.datasource.url=jdbc:postgresql://localhost:5432/cvtheque
spring.datasource.url=jdbc:postgresql://151.80.232.16:5432/cvtheque
spring.datasource.username=postgres
spring.datasource.password=Az@zel84
spring.datasource.driver-class-name=org.postgresql.Driver


