#Server and Logging errors
spring.application.name=cvtheque
server.port = 8090
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=ERROR
spring.jackson.serialization.fail-on-empty-beans=false

#JWT
jwt.secret=fsdf+34jkk558-gjl57o

#Storage Service
spring.servlet.multipart.max-file-size=50000KB
spring.servlet.multipart.max-request-size=50000KB

#Gmail Server configuration 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=azaheni@smartgraphe.com
spring.mail.password=fsdf+34jkk558-gjl57o
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


#Tuning Hikari Configuration Parameters
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000

###Database : POSTGRESQL
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

###Database : Paramètres partagés
spring.datasource.username=postgres
spring.datasource.password=Az@zel84
spring.datasource.driver-class-name=org.postgresql.Driver

### DEV ###
#spring.datasource.url=jdbc:postgresql://localhost:5432/cvtheque

### PROD OVH ###
spring.datasource.url=jdbc:postgresql://ats.odix.fr:5432/cvtheque


### PROD RDS AWS ###
#spring.datasource.username=postgres
#spring.datasource.password=Azazel84
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://cvtheque.cxzhv9oppuzk.us-east-2.rds.amazonaws.com:5432/postgres

###AWS S3 ###
#Disable Spring Cloud AWS autoconfiguration for local development
#cloud.aws.region.auto=false
#cloud.aws.region.static=us-east-1
#cloud.aws.stack.auto = false


#https://www.linkedin.com/developers/apps/13241553/auth
linkedin.consumerKey=77gwc32hbovbzc
linkedin.consumerSecret=lE5VwrZAh7rDQJ2U
linkedin.scope=r_liteprofile r_emailaddress 
#linkedin.redirectUri=http://localhost:4200/redirect-linkedin
linkedin.redirectUri=https://www.ats.odix.fr/redirect-linkedin
linkedin.state=fsdf-34jkk558-gjl57o
#https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin
linkedin.urlLiteProfile=https://api.linkedin.com/v2/me
linkedin.urlEmailaddress=https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))
linkedin.urlProfilePicture=https://api.linkedin.com/v2/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))



